name: env_cpa
channels:
   - conda-forge
   - anaconda
dependencies:
   - python=3.11.4
   - conda-build

   # analysis tools
   - numpy>=1.25.0
   - astropy>=5.3
   - scipy>=1.11.1
   - pandas>=2.0.3
   - iminuit=2.22.0

   # cpp libraries
   - nlohmann_json=3.11.2

   # ROOT CERN
  #  - uproot>=5.0.9
   - root=6.28.0

   # plotting
   - matplotlib>=3.7.1

   # miscellaneous
  #  - fortranformat=1.2.2
   - ipykernel>=6.23.3
