#!/usr/bin/env python3

import pathlib
import subprocess

def main():
    conda_pth = subprocess.run('which conda', shell=True, capture_output=True, text=True)
    conda_pth = pathlib.Path(conda_pth.stdout.strip()).parent.parent.absolute()
    print(conda_pth)

if __name__ == '__main__':
    main()